"""
orthoswift_post.report
======================

Client-ready PDF generation for inspection and agriculture jobs.

Uses ReportLab (https://www.reportlab.com/docs/reportlab-userguide.pdf),
which is the long-standing Python PDF library used by countless commercial
GIS reporting stacks. Pure-Python, no external service required.

Design:
* One-page summary by default. A second page is added if there are >5
  flagged zones or >5 stockpiles/hotspots.
* All numbers come from the analytics layer. No fabricated values.
* Conservative language ("candidate", "estimated", "review suggested")
  per the product brief.
"""
from __future__ import annotations

from pathlib import Path
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Image,
                                Table, TableStyle)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# Register bundled OrthoSWIFT brand fonts when available.
font_dir = Path(__file__).parent.parent / "assets" / "fonts"
font_path = font_dir / "SpaceGrotesk-Bold.ttf"
inter_path = font_dir / "InterVariable.ttf"

USE_SPACE_GROTESK = False
if font_path.exists():
    try:
        pdfmetrics.registerFont(TTFont("SpaceGrotesk", str(font_path)))
        USE_SPACE_GROTESK = True
    except Exception:
        pass

USE_INTER = False
if inter_path.exists():
    try:
        pdfmetrics.registerFont(TTFont("Inter", str(inter_path)))
        USE_INTER = True
    except Exception:
        pass


def _styles():
    s = getSampleStyleSheet()
    
    title_font = "SpaceGrotesk" if USE_SPACE_GROTESK else "Helvetica-Bold"
    body_font = "Inter" if USE_INTER else "Helvetica"
    
    s["Normal"].fontName = body_font
    s["BodyText"].fontName = body_font
    s["Heading1"].fontName = title_font
    s["Heading2"].fontName = title_font
    
    s.add(ParagraphStyle(name="Small", parent=s["BodyText"], fontName=body_font, fontSize=8,
                         leading=10, textColor=colors.grey))
    s.add(ParagraphStyle(name="H1", parent=s["Heading1"], fontName=title_font, fontSize=18,
                         leading=22))
    s.add(ParagraphStyle(name="H2", parent=s["Heading2"], fontName=title_font, fontSize=12,
                         leading=15))
    return s


def _table(data, col_widths=None):
    t = Table(data, colWidths=col_widths, hAlign="LEFT")
    font_name = "Inter" if USE_INTER else "Helvetica"
    header_font = "SpaceGrotesk" if USE_SPACE_GROTESK else "Helvetica-Bold"
    
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), header_font),
        ("FONTNAME", (0, 1), (-1, -1), font_name),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.whitesmoke, colors.white]),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
    ]))
    return t


def _draw_footer(canvas_obj, doc):
    canvas_obj.saveState()
    canvas_obj.setFont("Helvetica-Oblique", 8)
    canvas_obj.setFillColor(colors.HexColor("#666666"))
    
    footer_text = "Generated by OrthoSWIFT | www.orthoswift.net"
    width, height = doc.pagesize
    footer_width = canvas_obj.stringWidth(footer_text, "Helvetica-Oblique", 8)
    footer_x = (width - footer_width) / 2
    canvas_obj.drawString(footer_x, 10 * mm, footer_text)
    canvas_obj.restoreState()


# --------------------------------------------------------------------------
# Inspection PDF
# --------------------------------------------------------------------------



# --------------------------------------------------------------------------
# Agriculture PDF
# --------------------------------------------------------------------------
def build_agriculture_pdf(
    out_path: str | Path,
    *,
    ortho_preview: str | Path,
    ndvi_preview: str | Path,
    zone_table: Optional[list] = None,
    hotspot_table: Optional[list] = None,
    canopy_cover_pct: Optional[float] = None,
    coverage_metrics: Optional[dict] = None,
    fertilizer_rate_summary: Optional[dict] = None,
    spot_spray_rate_summary: Optional[dict] = None,
    disclaimer: Optional[str] = None,
) -> Path:
    """Build farmer-facing agriculture PDF.

    The wording intentionally avoids GIS jargon. Internally, the values may come
    from rasters, masks, and vector polygons, but the report should describe the
    output in field/operator language.
    """
    s = _styles()
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
    )
    story = []

    story.append(Paragraph("Field Health Summary", s["H1"]))
    story.append(Spacer(1, 6))

    img_w = 85 * mm
    img_h = 60 * mm
    imgs = [
        Image(str(ortho_preview), width=img_w, height=img_h),
        Image(str(ndvi_preview), width=img_w, height=img_h),
    ]
    story.append(Table([imgs], hAlign="LEFT"))
    story.append(Paragraph(
        "Left: field map preview. Right: crop-health map preview.",
        s["Small"],
    ))
    story.append(Spacer(1, 8))

    # ------------------------------------------------------------------
    # Vegetation cover in valid multispectral footprint
    # ------------------------------------------------------------------
    if canopy_cover_pct is not None:
        story.append(Paragraph("Vegetation cover in valid multispectral footprint", s["H2"]))

        cover_rows = [
            ["Metric", "Value"],
            [
                "Broad NDVI vegetation cover in finite multispectral footprint (%)",
                f"{canopy_cover_pct:.1f}",
            ],
        ]

        if coverage_metrics:
            usable_area = coverage_metrics.get("usable_field_area_m2")
            action_area = coverage_metrics.get("recommended_action_zone_area_m2")
            action_pct = coverage_metrics.get("recommended_action_zone_pct_of_usable_area")
            excluded_area = coverage_metrics.get("usable_area_not_in_action_zones_m2")

            if usable_area is not None:
                cover_rows.append(["Usable field area analyzed (m²)", f"{float(usable_area):.1f}"])
            if action_area is not None:
                cover_rows.append(["Recommended action-zone area (m²)", f"{float(action_area):.1f}"])
            if action_pct is not None:
                cover_rows.append(["Action zones as % of usable area", f"{float(action_pct):.1f}"])
            if excluded_area is not None:
                cover_rows.append(["Usable area outside action zones (m²)", f"{float(excluded_area):.1f}"])

        story.append(_table(cover_rows, col_widths=[95 * mm, 45 * mm]))
        story.append(Paragraph(
            "Vegetation cover is the percentage of finite, co-registered "
            "multispectral pixels with NDVI at or above 0.20. It is a broad "
            "optical vegetation-cover metric. It is not calculated from the "
            "cleaned crop-domain mask and may include weeds or other vegetation.",
            s["Small"],
        ))
        story.append(Spacer(1, 8))

    # ------------------------------------------------------------------
    # Fertilizer application-rate plan
    # ------------------------------------------------------------------
    if fertilizer_rate_summary:
        story.append(Paragraph("Fertilizer application-rate plan", s["H2"]))
        mode = str(fertilizer_rate_summary.get("mode", "relative"))
        if mode == "physical":
            rows = [
                ["Field", "Operator-supplied value"],
                ["Product", str(fertilizer_rate_summary.get("product_name", ""))],
                ["Rate basis", str(fertilizer_rate_summary.get("rate_basis", ""))],
                ["Strategy", str(fertilizer_rate_summary.get("strategy", "")).replace("_", " ")],
                ["Approved by", str(fertilizer_rate_summary.get("approved_by", ""))],
                ["Resolved rate range", f"{float(fertilizer_rate_summary.get('resolved_min_rate', 0)):g}–{float(fertilizer_rate_summary.get('resolved_max_rate', 0)):g} {fertilizer_rate_summary.get('unit', '')}"],
                ["Treated area (ha)", f"{float(fertilizer_rate_summary.get('treated_area_ha', 0)):.3f}"],
            ]
            if fertilizer_rate_summary.get("estimated_total_product") is not None:
                rows.append(["Estimated total product", f"{float(fertilizer_rate_summary['estimated_total_product']):,.2f} {fertilizer_rate_summary.get('total_product_unit', '')}"])
            story.append(_table(rows, col_widths=[65 * mm, 95 * mm]))
            story.append(Paragraph(
                "These physical rates were supplied and approved upstream by the named operator or agronomist. "
                "OrthoSWIFT assigned them spatially; it did not infer fertilizer dose from NDVI/NDRE. Verify the "
                "product, units, boundaries, equipment limits, calibration, and controller preview before applying.",
                s["Small"],
            ))
        else:
            story.append(Paragraph(
                "No approved physical fertilizer-rate plan was supplied. Controller files contain relative "
                "0–100% intensity values. Assign and verify physical rates in the controller or farm-management software.",
                s["Small"],
            ))
        story.append(Spacer(1, 8))

    # ------------------------------------------------------------------
    # Spot-spraying application plan
    # ------------------------------------------------------------------
    if spot_spray_rate_summary:
        story.append(Paragraph("Spot-spraying application plan", s["H2"]))
        mode = str(spot_spray_rate_summary.get("mode", "relative"))
        if mode == "physical":
            rows = [
                ["Field", "Operator-supplied value"],
                ["Product", str(spot_spray_rate_summary.get("product_name", ""))],
                ["Approved by", str(spot_spray_rate_summary.get("approved_by", ""))],
                ["Target rate (on hotspot)", f"{float(spot_spray_rate_summary.get('target_rate', 0)):g} {spot_spray_rate_summary.get('unit', '')}"],
                ["Background rate (off hotspot)", f"0 {spot_spray_rate_summary.get('unit', '')} (shutoff)"],
                ["Targeted hotspot area (ha)", f"{float(spot_spray_rate_summary.get('treated_area_ha', 0)):.3f}"],
            ]
            if spot_spray_rate_summary.get("estimated_total_product") is not None:
                rows.append(["Estimated total product", f"{float(spot_spray_rate_summary['estimated_total_product']):,.2f} {spot_spray_rate_summary.get('total_product_unit', '')}"])
            story.append(_table(rows, col_widths=[65 * mm, 95 * mm]))
            story.append(Paragraph(
                "These physical spot-spray rates were supplied and approved upstream by the named operator. "
                "OrthoSWIFT encoded them into spot-spraying controller packages for targeted nozzle/section activation.",
                s["Small"],
            ))
        else:
            story.append(Paragraph(
                "No approved physical spot-spray rate was supplied. Controller files contain binary section-control "
                "commands (100% on targets, 0% background). Assign real product rates in the controller.",
                s["Small"],
            ))
        story.append(Spacer(1, 8))

    # ------------------------------------------------------------------
    # Recommended action zones
    # ------------------------------------------------------------------
    if zone_table:
        story.append(Paragraph("Recommended action zones", s["H2"]))
        story.append(_table(zone_table))
        story.append(Paragraph(
            "These zones show the main areas OrthoSWIFT found for review or treatment planning. "
            "Very small or broken-up areas may be excluded so the exported files stay practical for equipment and field use.",
            s["Small"],
        ))
        story.append(Spacer(1, 8))

    # ------------------------------------------------------------------
    # Low-vigor scouting targets
    # ------------------------------------------------------------------
    story.append(Paragraph("Low-vigor scouting targets", s["H2"]))
    if hotspot_table:
        story.append(_table(hotspot_table))
        story.append(Paragraph(
            "Targets are low-vigor areas for review and scouting. Confirm the cause in the field before acting.",
            s["Small"],
        ))
    else:
        story.append(Paragraph(
            "No low-vigor target area passed the minimum size and quality filters for this run, so no separate target file was generated.",
            s["Small"],
        ))
    story.append(Spacer(1, 8))

    # ------------------------------------------------------------------
    story.append(Paragraph("Operational Note & Calibration Disclaimers", s["H2"]))
    if disclaimer:
        story.append(Paragraph(disclaimer.replace("\n\n", "<br/><br/>"), s["Small"]))
        story.append(Spacer(1, 4))
    story.append(Paragraph(
        "OrthoSWIFT creates field-ready decision-support files from drone maps. "
        "The operator remains responsible for checking boundaries, choosing products, setting rates, confirming equipment settings, and following local rules.",
        s["Small"],
    ))

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    return Path(out_path)
