"""
orthoswift_post.report
======================

Client-ready PDF generation for inspection and agriculture jobs.

Uses ReportLab (https://www.reportlab.com/docs/reportlab-userguide.pdf),
which is the long-standing Python PDF library used by countless commercial
GIS reporting stacks. Pure-Python, no external service required.

Design:
* One-page summary by default. A second page is added if there are >5
  flagged zones or >5 stockpiles/hotspots.
* All numbers come from the analytics layer. No fabricated values.
* Conservative language ("candidate", "estimated", "review suggested")
  per the product brief.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# Register OrthoSWIFT brand fonts if available in plugin directory or assets/fonts/
plugin_dir = Path(__file__).parent.parent
_font_search = [plugin_dir, plugin_dir / "assets" / "fonts"]
font_path = next((d / "SpaceGrotesk-Bold.ttf" for d in _font_search if (d / "SpaceGrotesk-Bold.ttf").exists()), None)
inter_path = next((d / "InterVariable.ttf" for d in _font_search if (d / "InterVariable.ttf").exists()), None)

USE_SPACE_GROTESK = False
if font_path:
    try:
        pdfmetrics.registerFont(TTFont("SpaceGrotesk", str(font_path)))
        USE_SPACE_GROTESK = True
    except (OSError, ValueError) as exc:
        logger.debug("Could not register bundled heading font %s: %s", font_path, exc)

USE_INTER = False
if inter_path:
    try:
        pdfmetrics.registerFont(TTFont("Inter", str(inter_path)))
        USE_INTER = True
    except (OSError, ValueError) as exc:
        logger.debug("Could not register bundled body font %s: %s", inter_path, exc)


def _styles():
    s = getSampleStyleSheet()

    title_font = "SpaceGrotesk" if USE_SPACE_GROTESK else "Helvetica-Bold"
    body_font = "Inter" if USE_INTER else "Helvetica"

    s["Normal"].fontName = body_font
    s["BodyText"].fontName = body_font
    s["Heading1"].fontName = title_font
    s["Heading2"].fontName = title_font

    s.add(ParagraphStyle(name="Small", parent=s["BodyText"], fontName=body_font, fontSize=8,
                         leading=10, textColor=colors.grey))
    s.add(ParagraphStyle(name="H1", parent=s["Heading1"], fontName=title_font, fontSize=18,
                         leading=22))
    s.add(ParagraphStyle(name="H2", parent=s["Heading2"], fontName=title_font, fontSize=12,
                         leading=15))
    return s


def _table(data, col_widths=None):
    t = Table(data, colWidths=col_widths, hAlign="LEFT")
    font_name = "Inter" if USE_INTER else "Helvetica"
    header_font = "SpaceGrotesk" if USE_SPACE_GROTESK else "Helvetica-Bold"

    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), header_font),
        ("FONTNAME", (0, 1), (-1, -1), font_name),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.whitesmoke, colors.white]),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
    ]))
    return t


def _draw_footer(canvas_obj, doc):
    canvas_obj.saveState()
    canvas_obj.setFont("Helvetica-Oblique", 8)
    canvas_obj.setFillColor(colors.HexColor("#666666"))

    footer_text = "Generated by OrthoSWIFT | Fertilizer & Spray Prescriptions | www.orthoswift.net"
    width, _height = doc.pagesize
    footer_width = canvas_obj.stringWidth(footer_text, "Helvetica-Oblique", 8)
    footer_x = (width - footer_width) / 2
    canvas_obj.drawString(footer_x, 8 * mm, footer_text)
    canvas_obj.restoreState()


# Agriculture PDF
def build_agriculture_pdf(
    out_path: str | Path,
    *,
    ortho_preview: str | Path,
    ndvi_preview: str | Path,
    zone_table: Optional[list] = None,
    hotspot_table: Optional[list] = None,
    canopy_cover_pct: Optional[float] = None,
    coverage_metrics: Optional[dict] = None,
    fertilizer_rate_summary: Optional[dict] = None,
    spot_spray_rate_summary: Optional[dict] = None,
    disclaimer: Optional[str] = None,
    offline_basemap_included: bool = False,
    controller_packages_available: bool = False,
) -> Path:
    """Build an operator-ready fertilizer and spot-spray prescription report."""
    s = _styles()
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )
    story = []

    # Title & Subtitle
    story.append(Paragraph("Prescription Report", s["H1"]))
    story.append(Paragraph("Fertilizer zones, spot-spray targets & controller package summary", s["Small"]))
    story.append(Spacer(1, 4))

    # Dual Map Previews (Compact)
    img_w = 88 * mm
    img_h = 46 * mm
    imgs = [
        Image(str(ortho_preview), width=img_w, height=img_h),
        Image(str(ndvi_preview), width=img_w, height=img_h),
    ]
    story.append(Table([imgs], hAlign="LEFT"))
    story.append(Paragraph(
        "Left: RGB orthomosaic preview. Right: vegetation-index preview (NDVI when available).",
        s["Small"],
    ))
    story.append(Spacer(1, 5))

    # Field-level metrics are independent of either prescription operation.
    field_rows = [["Field Metric", "Value"]]
    if coverage_metrics:
        usable_area_m2 = coverage_metrics.get("usable_field_area_m2")
        mapped_area_m2 = coverage_metrics.get("recommended_action_zone_area_m2")
        if usable_area_m2 is not None:
            field_rows.append([
                "Analyzed Field Area",
                f"{float(usable_area_m2) / 10000.0:.2f} ha ({float(usable_area_m2):,.0f} m²)",
            ])
        if mapped_area_m2 is not None:
            field_rows.append([
                "Mapped Management-Zone Area",
                f"{float(mapped_area_m2) / 10000.0:.2f} ha ({float(mapped_area_m2):,.0f} m²)",
            ])
    if canopy_cover_pct is not None:
        field_rows.append(["Estimated Canopy Cover", f"{float(canopy_cover_pct):.1f}%"])
    if zone_table and len(zone_table) > 1:
        field_rows.append(["Fertilizer Management Zones", str(len(zone_table) - 1)])
    if hotspot_table and len(hotspot_table) > 1:
        field_rows.append(["Spot-Spray / Scouting Targets", str(len(hotspot_table) - 1)])
    story.append(Paragraph("Field Summary", s["H2"]))
    story.append(_table(field_rows, col_widths=[90 * mm, 90 * mm]))
    story.append(Spacer(1, 5))

    def plan_rows(summary, operation):
        rows = [["Plan Metric", "Plan Value"]]
        if not summary:
            rows.append(["Status", "No prescription summary was produced"])
            return rows
        mode = str(summary.get("mode", "relative"))
        rows.append(["Application Mode", "Physical rate plan" if mode == "physical" else "Relative intensity"])
        if summary.get("product_name"):
            rows.append(["Product", str(summary["product_name"])])
        if summary.get("strategy"):
            rows.append(["Strategy", str(summary["strategy"]).replace("_", " ").title()])
        unit = str(summary.get("unit", ""))
        if operation == "fertilizer":
            minimum = summary.get("resolved_min_rate")
            maximum = summary.get("resolved_max_rate")
            if minimum is not None and maximum is not None:
                label = "Prescribed Rate Range" if mode == "physical" else "Prescribed Intensity Range"
                rows.append([label, f"{float(minimum):g}–{float(maximum):g} {unit}"])
        else:
            target = summary.get("target_rate")
            background = summary.get("background_rate", 0)
            if target is not None:
                rows.append(["Target / Background Rate", f"{float(target):g} / {float(background):g} {unit}"])
        if summary.get("treated_area_ha") is not None:
            rows.append(["Treated Area", f"{float(summary['treated_area_ha']):.2f} ha"])
        if summary.get("estimated_total_product") is not None:
            rows.append([
                "Estimated Total Product",
                f"{float(summary['estimated_total_product']):,.2f} {summary.get('total_product_unit', '')}",
            ])
        if summary.get("approved_by"):
            rows.append(["Plan Approved By", str(summary["approved_by"])])
        return rows

    story.append(Paragraph("Fertilizer Prescription Summary", s["H2"]))
    story.append(_table(plan_rows(fertilizer_rate_summary, "fertilizer"), col_widths=[90 * mm, 90 * mm]))
    story.append(Spacer(1, 5))

    if spot_spray_rate_summary:
        story.append(Paragraph("Spot-Spray Prescription Summary", s["H2"]))
        story.append(_table(plan_rows(spot_spray_rate_summary, "spray"), col_widths=[90 * mm, 90 * mm]))
        story.append(Spacer(1, 5))

    # Prescription Zones Table
    if zone_table and len(zone_table) > 1:
        story.append(Paragraph("Fertilizer Management Zones", s["H2"]))
        story.append(_table(zone_table))
        story.append(Spacer(1, 5))

    # Ground Scouting Checkpoints (Hotspots) - Keep top 5 max for brevity
    if hotspot_table and len(hotspot_table) > 1:
        story.append(Paragraph("Spot-Spray & Ground-Scouting Targets", s["H2"]))
        compact_hotspots = [hotspot_table[0]] + hotspot_table[1:6]
        story.append(_table(compact_hotspots))
        story.append(Spacer(1, 5))

    # Machine USB Setup & Quick-Load Reference
    if controller_packages_available:
        setup_rows = [
            ["System", "ZIP Package", "USB Destination Path"],
            ["DJI Agras", "dji_agras.zip", "USB:/DJI/"],
        ]
        story.append(Paragraph("Machine USB Loading Reference", s["H2"]))
        story.append(_table(setup_rows, col_widths=[60 * mm, 60 * mm, 66 * mm]))
        basemap_note = (
            "The exported controller ZIP includes Basemap/orthomosaic.mbtiles for offline field imagery."
            if offline_basemap_included
            else "Offline MBTiles were disabled; the exported controller ZIP does not include a basemap."
        )
        story.append(Paragraph(
            "Extract `dji_agras.zip` so its DJI folder is at the USB root. " + basemap_note,
            s["Small"],
        ))
    else:
        story.append(Paragraph("Controller Package Status", s["H2"]))
        story.append(Paragraph(
            "No machine controller package was produced. Review the operational notices and processing warnings before field use.",
            s["Small"],
        ))
    story.append(Spacer(1, 5))

    # Operational Notice & Disclaimers
    story.append(Paragraph("Operational Notice", s["H2"]))
    if disclaimer:
        story.append(Paragraph(disclaimer.replace("\n\n", "<br/>"), s["Small"]))
        story.append(Spacer(1, 2))
    story.append(Paragraph(
        "Prescriptions are formatted for DJI Agras workflows. "
        "Verify agronomic rates, product labels, equipment calibration, field boundaries, and spray conditions before applying.",
        s["Small"],
    ))

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    return Path(out_path)
