"""
orthoswift_post.report
======================

Client-ready PDF generation for inspection and agriculture jobs.

Uses ReportLab (https://www.reportlab.com/docs/reportlab-userguide.pdf),
which is the long-standing Python PDF library used by countless commercial
GIS reporting stacks. Pure-Python, no external service required.

Design:
* One-page summary by default. A second page is added if there are >5
  flagged zones or >5 stockpiles/hotspots.
* All numbers come from the analytics layer. No fabricated values.
* Conservative language ("candidate", "estimated", "review suggested")
  per the product brief.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# Register OrthoSWIFT brand fonts if available in plugin directory or assets/fonts/
plugin_dir = Path(__file__).parent.parent
_font_search = [plugin_dir, plugin_dir / "assets" / "fonts"]
font_path = next((d / "SpaceGrotesk-Bold.ttf" for d in _font_search if (d / "SpaceGrotesk-Bold.ttf").exists()), None)
inter_path = next((d / "InterVariable.ttf" for d in _font_search if (d / "InterVariable.ttf").exists()), None)

USE_SPACE_GROTESK = False
if font_path:
    try:
        pdfmetrics.registerFont(TTFont("SpaceGrotesk", str(font_path)))
        USE_SPACE_GROTESK = True
    except (OSError, ValueError) as exc:
        logger.debug("Could not register bundled heading font %s: %s", font_path, exc)

USE_INTER = False
if inter_path:
    try:
        pdfmetrics.registerFont(TTFont("Inter", str(inter_path)))
        USE_INTER = True
    except (OSError, ValueError) as exc:
        logger.debug("Could not register bundled body font %s: %s", inter_path, exc)


def _styles():
    s = getSampleStyleSheet()

    title_font = "SpaceGrotesk" if USE_SPACE_GROTESK else "Helvetica-Bold"
    body_font = "Inter" if USE_INTER else "Helvetica"

    s["Normal"].fontName = body_font
    s["BodyText"].fontName = body_font
    s["Heading1"].fontName = title_font
    s["Heading2"].fontName = title_font

    s.add(ParagraphStyle(name="Small", parent=s["BodyText"], fontName=body_font, fontSize=8,
                         leading=10, textColor=colors.grey))
    s.add(ParagraphStyle(name="H1", parent=s["Heading1"], fontName=title_font, fontSize=18,
                         leading=22))
    s.add(ParagraphStyle(name="H2", parent=s["Heading2"], fontName=title_font, fontSize=12,
                         leading=15))
    return s


def _table(data, col_widths=None):
    t = Table(data, colWidths=col_widths, hAlign="LEFT")
    font_name = "Inter" if USE_INTER else "Helvetica"
    header_font = "SpaceGrotesk" if USE_SPACE_GROTESK else "Helvetica-Bold"

    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), header_font),
        ("FONTNAME", (0, 1), (-1, -1), font_name),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1),
         [colors.whitesmoke, colors.white]),
        ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
    ]))
    return t


def _draw_footer(canvas_obj, doc):
    canvas_obj.saveState()
    canvas_obj.setFont("Helvetica-Oblique", 8)
    canvas_obj.setFillColor(colors.HexColor("#666666"))

    footer_text = "Generated by OrthoSWIFT | Spray & Application Prescriptions | www.orthoswift.net"
    width, _height = doc.pagesize
    footer_width = canvas_obj.stringWidth(footer_text, "Helvetica-Oblique", 8)
    footer_x = (width - footer_width) / 2
    canvas_obj.drawString(footer_x, 8 * mm, footer_text)
    canvas_obj.restoreState()


# Agriculture PDF
def build_agriculture_pdf(
    out_path: str | Path,
    *,
    ortho_preview: str | Path,
    ndvi_preview: str | Path,
    zone_table: Optional[list] = None,
    hotspot_table: Optional[list] = None,
    canopy_cover_pct: Optional[float] = None,
    coverage_metrics: Optional[dict] = None,
    fertilizer_rate_summary: Optional[dict] = None,
    spot_spray_rate_summary: Optional[dict] = None,
    disclaimer: Optional[str] = None,
) -> Path:
    """Build brief, operator-ready spray report."""
    s = _styles()
    doc = SimpleDocTemplate(
        str(out_path),
        pagesize=A4,
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=12 * mm,
        bottomMargin=12 * mm,
    )
    story = []

    # Title & Subtitle
    story.append(Paragraph("Spray Report", s["H1"]))
    story.append(Paragraph("Precision prescription package & tank-mix summary", s["Small"]))
    story.append(Spacer(1, 4))

    # Dual Map Previews (Compact)
    img_w = 88 * mm
    img_h = 46 * mm
    imgs = [
        Image(str(ortho_preview), width=img_w, height=img_h),
        Image(str(ndvi_preview), width=img_w, height=img_h),
    ]
    story.append(Table([imgs], hAlign="LEFT"))
    story.append(Paragraph(
        "Left: RGB field basemap. Right: Prescription spray zones & targets.",
        s["Small"],
    ))
    story.append(Spacer(1, 5))

    # Application & Tank-Mix Summary Table
    summary_rows = [["Application & Coverage Metric", "Plan Value"]]

    rate_summary = spot_spray_rate_summary or fertilizer_rate_summary or {}
    mode = str(rate_summary.get("mode", "relative"))
    product = rate_summary.get("product_name")

    if product:
        summary_rows.append(["Product", str(product)])

    if mode == "physical":
        if "target_rate" in rate_summary:
            summary_rows.append(["Target Application Rate", f"{float(rate_summary.get('target_rate', 0)):g} {rate_summary.get('unit', '')}"])
        elif "resolved_min_rate" in rate_summary:
            summary_rows.append(["Prescribed Rate Range", f"{float(rate_summary.get('resolved_min_rate', 0)):g}–{float(rate_summary.get('resolved_max_rate', 0)):g} {rate_summary.get('unit', '')}"])

        if rate_summary.get("estimated_total_product") is not None:
            summary_rows.append(["Total Product to Mix in Tank", f"{float(rate_summary['estimated_total_product']):,.2f} {rate_summary.get('total_product_unit', '')}"])

        if rate_summary.get("approved_by"):
            summary_rows.append(["Plan Approved By", str(rate_summary["approved_by"])])
    else:
        summary_rows.append(["Application Mode", "Relative 0–100% intensity (set tank rate on machine)"])

    if coverage_metrics:
        usable_area_m2 = coverage_metrics.get("usable_field_area_m2")
        action_area_m2 = coverage_metrics.get("recommended_action_zone_area_m2")
        if usable_area_m2 is not None:
            usable_ha = float(usable_area_m2) / 10000.0
            summary_rows.append(["Total Field Area", f"{usable_ha:.2f} ha ({float(usable_area_m2):,.0f} m²)"])
        if action_area_m2 is not None and usable_area_m2:
            action_ha = float(action_area_m2) / 10000.0
            action_pct = (float(action_area_m2) / float(usable_area_m2)) * 100.0
            savings_pct = max(0.0, 100.0 - action_pct)
            summary_rows.append(["Targeted Treatment Area", f"{action_ha:.2f} ha ({action_pct:.1f}% of field)"])
            if savings_pct > 0.1:
                summary_rows.append(["Chemical / Area Savings vs Broadcast", f"{savings_pct:.1f}% reduction"])
    elif rate_summary.get("treated_area_ha") is not None:
        summary_rows.append(["Targeted Treatment Area", f"{float(rate_summary['treated_area_ha']):.2f} ha"])

    story.append(Paragraph("Application & Tank-Mix Summary", s["H2"]))
    story.append(_table(summary_rows, col_widths=[90 * mm, 90 * mm]))
    story.append(Spacer(1, 5))

    # Prescription Zones Table
    if zone_table and len(zone_table) > 1:
        story.append(Paragraph("Prescription Zones", s["H2"]))
        story.append(_table(zone_table))
        story.append(Spacer(1, 5))

    # Ground Scouting Checkpoints (Hotspots) - Keep top 5 max for brevity
    if hotspot_table and len(hotspot_table) > 1:
        story.append(Paragraph("Pre-Spray Ground Scouting Checkpoints", s["H2"]))
        compact_hotspots = [hotspot_table[0]] + hotspot_table[1:6]
        story.append(_table(compact_hotspots))
        story.append(Spacer(1, 5))

    # Machine USB Setup & Quick-Load Reference
    setup_rows = [
        ["System", "ZIP Package", "USB Destination Path"],
        ["DJI Agras", "dji_agras.zip", "USB:/DJI/"],
    ]
    story.append(Paragraph("Machine USB Loading Reference", s["H2"]))
    story.append(_table(setup_rows, col_widths=[60 * mm, 60 * mm, 66 * mm]))
    story.append(Paragraph(
        "Extract `dji_agras.zip` so its DJI folder is at the USB root. "
        "Each ZIP includes Basemap/orthomosaic.mbtiles for in-cab offline field imagery.",
        s["Small"],
    ))
    story.append(Spacer(1, 5))

    # Operational Notice & Disclaimers
    story.append(Paragraph("Operational Notice", s["H2"]))
    if disclaimer:
        story.append(Paragraph(disclaimer.replace("\n\n", "<br/>"), s["Small"]))
        story.append(Spacer(1, 2))
    story.append(Paragraph(
        "Prescriptions are formatted for DJI Agras workflows. "
        "Verify product labels, tank mix calibration, drift conditions, and machine boundaries before applying.",
        s["Small"],
    ))

    doc.build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    return Path(out_path)
